const sheetRanges = {
  USUARIOS: 'A1:E30',
  REGISTROS: 'A1:I50',
  SOLICITUDES: 'A1:E50',
  ACTIVIDADES: 'A1:I80',
  ACTIVIDAD_ACTOR: 'A1:C50',
  PROCESOS: 'A1:B50',
  ADJUNTOS_ACTIVIDADES: 'A1:C50',
  DATOS_INICIALES_SOLICITUD: 'A1:E50',
  RECORDATORIOS: 'A1:C50',
  PROGRAMAS: 'A1:B90',
  DOCUMENTOS: 'A1:D50',
};

module.exports = {
  sheetRanges,
};
