const sheetRanges = {
  USUARIOS: 'A1:E4',
  REGISTROS: 'A1:H50',
  SOLICITUDES: 'A1:E50',
  ACTIVIDADES: 'A1:G80',
  ACTIVIDAD_ACTOR: 'A1:C50',
  PROCESOS: 'A1:B50',
  ADJUNTOS_ACTIVIDADES: 'A1:C50',
  DATOS_INICIALES_SOLICITUD: 'A1:D50',
  RECORDATORIOS: 'A1:C50',
};

module.exports = {
  sheetRanges,
};
